### ISSUE TITLE
android.view.WindowManager$BadTokenException: Permission denied for this window type

### ISSUE THREAD

**Issue by Armaxis** [xfumihiro/ViewInspector#18]
I'm using a `0.1.2-SNAPSHOT` version of library and my app crashes at startup. Can't use `0.1.1` because of bug with WebViews.
I do have a permission `android.permission.SYSTEM_ALERT_WINDOW` in my `AndroidManifest.xml`

```
 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.armaxis.mobile/com.armaxis.mobile.StartupActivity}: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@3fb6060 -- permission denied for this window type
     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
     at android.app.ActivityThread.-wrap11(ActivityThread.java)
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
     at android.os.Handler.dispatchMessage(Handler.java:102)
     at android.os.Looper.loop(Looper.java:148)
     at android.app.ActivityThread.main(ActivityThread.java:5417)
     at java.lang.reflect.Method.invoke(Native Method)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@3fb6060 -- permission denied for this window type
     at android.view.ViewRootImpl.setView(ViewRootImpl.java:591)
     at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:310)
     at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
     at view_inspector.weaving.ViewInspectorAspect.injectViewInspector(ViewInspectorAspect.java:82)
     at com.armaxis.mobile.StartupActivity.onCreate(StartupActivity.java:36)
     at android.app.Activity.performCreate(Activity.java:6237)
     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
     at android.app.ActivityThread.-wrap11(ActivityThread.java) 
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
     at android.os.Handler.dispatchMessage(Handler.java:102) 
     at android.os.Looper.loop(Looper.java:148) 
     at android.app.ActivityThread.main(ActivityThread.java:5417) 
     at java.lang.reflect.Method.invoke(Native Method) 
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

**Comment by xfumihiro** [comment]
@Armaxis What API level are you on?

**Comment by Armaxis** [comment]
Api 23

**Comment by vkotovv** [comment]
Had the same crash. It is because of [new permission system](https://github.com/xfumihiro/ViewInspector/issues/10) in Android 6.0.

**Comment by xfumihiro** [comment]
Duplicate of #10

**Comment by khuranakaran** [comment]
having same trouble, is there any way to get rid of this crash?

**Comment by xfumihiro** [comment]
@khuranakaran This should be fixed already. Are you using the latest version?

**Comment by khuranakaran** [comment]
yes i am using the latest version, but still getting same problem. What else should i do??

**Comment by xfumihiro** [comment]
have you set compileSdkVersion & targetSdkVerion to 23 ?

**Comment by xfumihiro** [comment]
It's funny that you can set compileSdkVerion < 23 and targetSdkVerion = 23 which will reproduce this issue. Clearly a bug of android gradle plugin to me.

**Comment by khuranakaran** [comment]
@xfumihiro yes both compileSdkVersion & targetSdkVerion are set to 23.

**Comment by xfumihiro** [comment]
can you check the output of `./gradlew clean assembleDebug` and see if prepareComGithubXfumihiroViewInspectorViewInspectorAspectV23021SNAPSHOTLibrary
is shown instead of prepareComGithubXfumihiroViewInspectorViewInspectorAspect021SNAPSHOTLibrary

**Comment by xfumihiro** [comment]
the V23 aspect module should be used if you set compileSdkVersion to 23

**Comment by xfumihiro** [comment]
try set the sample app's compileSdkVersion & targetSdkVersion to 23.
It should work.

**Comment by khuranakaran** [comment]
@xfumihiro yes i have been using V23 aspect module and versions are set to 23, and still same error...
![giterror](https://cloud.githubusercontent.com/assets/12525440/11652314/f6b3283c-9dbc-11e5-8b4a-0711102cb9ab.png)

**Comment by xfumihiro** [comment]
It's a NPE, not the same issue.

**Comment by khuranakaran** [comment]
but when i run on a device with Lollipop it run fine, whereas when run on device with Marshmallow i get this error.

**Comment by xfumihiro** [comment]
did it works without applying ViewInspector plugin ?

**Comment by khuranakaran** [comment]
yes without applying ViewInspector it runs perfect on Lollipop device

**Comment by xfumihiro** [comment]
I mean on Marshmallow

**Comment by khuranakaran** [comment]
nope it didn't work with and without ViewInspector on Marshmallow.

**Comment by xfumihiro** [comment]
so it's not the bug of this plugin

**Comment by khuranakaran** [comment]
yes.

**Comment by xfumihiro** [comment]
Happy debugging' :coffee:

**Comment by khuranakaran** [comment]
can you suggesrt any possible solution to this problem.
