### ISSUE TITLE
java.lang.NoSuchFieldError

### ISSUE THREAD

**Issue by Ivolian** [xfumihiro/ViewInspector#49]
java.lang.NoSuchFieldError: No static field toggle_menu of type I in class Lview_inspector/R$id; or its superclasses (declaration of 'view_inspector.R$id' appears in /data/app/com.unicorn.csp.xcdemo-1/base.apk)
     at view_inspector.ui.ViewInspectorToolbar.onAttachedToWindow(ViewInspectorToolbar.java:90)
     at android.view.View.dispatchAttachedToWindow(View.java:13543)
     at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2690)
     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1322)
     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1084)
     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5990)
     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
     at android.view.Choreographer.doCallbacks(Choreographer.java:580)
     at android.view.Choreographer.doFrame(Choreographer.java:550)
     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
     at android.os.Handler.handleCallback(Handler.java:739)
     at android.os.Handler.dispatchMessage(Handler.java:95)
     at android.os.Looper.loop(Looper.java:135)
     at android.app.ActivityThread.main(ActivityThread.java:5343)
     at java.lang.reflect.Method.invoke(Native Method)
     at java.lang.reflect.Method.invoke(Method.java:372)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

**Comment by xfumihiro** [comment]
0.1.4 or 0.2.0-SNAPSHOT?

**Comment by Ivolian** [comment]
@xfumihiro I tried both of them, the same error.

**Comment by xfumihiro** [comment]
@Ivolian Do you have a layout file "toolbar.xml" in your app?

**Comment by xfumihiro** [comment]
@Ivolian It should work now on 0.2.0-SNAPSHOT.

**Comment by Ivolian** [comment]
@xfumihiro
I delete the 0.2.0-SNAPSHOT local cache, and download it again.
However, the error still happened.
I rename toolbar.xml to m_toolbar.xml , it can work.

**Comment by xfumihiro** [comment]
@Ivolian I've republished the 0.2.0-SNAPSHOT. Please try again. The 0.2.0 version might take a while...

**Comment by Ivolian** [comment]
@xfumihiro  it works.
